[package]
name = "discordfs-server"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
discordfs-core.workspace = true
discordfs-protocol.workspace = true
discordfs-db.workspace = true
discordfs-objectstore.workspace = true
discordfs-crypto.workspace = true
discordfs-discord = { path = "../discordfs-discord" }
blake3 = { workspace = true }
getrandom = "0.2"

tokio.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
async-trait.workspace = true
parking_lot.workspace = true
bytes.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
async-trait = { workspace = true }
bytes = { workspace = true }
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1"
sqlx = { workspace = true }
